src/Presenters/RookEcomShop.CustomerFrontend/Controllers/CollectionsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RookEcomShop.Application.Dto;
using RookEcomShop.CustomerFrontend.Models;
using RookEcomShop.CustomerFrontend.Services.Categories;
using RookEcomShop.CustomerFrontend.Services.Products;
using RookEcomShop.ViewModels.ViewModels;
using Serilog;
using System.Diagnostics;

namespace RookEcomShop.CustomerFrontend.Controllers;

[Route("collections")]
public class CollectionsController : Controller
{
    private readonly IProductsApiClient _productsApiClient;
    private readonly ICategoriesApiClient _categoriesApiClient;

    public CollectionsController(
        IProductsApiClient productsApiClient,
        ICategoriesApiClient categoriesApiClient)
    {
        _productsApiClient = productsApiClient;
        _categoriesApiClient = categoriesApiClient;
    }

    [HttpGet("{categoryName}")]
    public async Task<ViewResult> Details(string categoryName, [FromQuery] ProductQueryDto queryDto)
    {

        Log.Information("[CollectionsController]: Get category from API " + categoryName);
        ViewBag.CategoryName = categoryName;
        var category = await _categoriesApiClient.GetCategoryByNameAsync(categoryName);

        if (category == null)
        {
            return View("NotFound");
        }

        queryDto.CategoryName = categoryName;
        queryDto.PageSize = 8;

        Log.Information("[CollectionsController]: Get products from API " + JsonConvert.SerializeObject(queryDto));
        var products = await _productsApiClient.GetProductsAsync(queryDto);

        SetUrlParams(queryDto);

        return View(new CollectionsVM
        {
            Category = category,
            Products = products
        });
    }

    private void SetUrlParams(ProductQueryDto queryDto)
    {
        ViewBag.SearchTerm = queryDto.SearchTerm;
        ViewBag.SortColumn = queryDto.SortColumn;
        ViewBag.SortOrder = queryDto.SortOrder;
        ViewBag.Page = queryDto.Page;
        ViewBag.PageSize = queryDto.PageSize;
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Presenters/RookEcomShop.CustomerFrontend/Views/Shared/Components/Sidebar/Default.cshtml
@using RookEcomShop.ViewModels.Dto
@model List<CategoryDto>
@section PageScripts {
    <script src="~/js/side-bar.js"></script>
}


<aside class="sidebar-wrapper">
    <div class="sidebar-container">
        <div class="h-16 flex-center text-center border-b border-gray-300">
            <h1 class="text-xl font-semibold">
                RookEcomShop
            </h1>
        </div>
        <div class="px-6">
            <section class="sidebar-section">
                <h3 class="text-lg font-semibold mb-3">Category</h3>
                <ul class="category-list space-y-4">
                    @foreach (var category in @Model)
                    {
                        <li>
                            <a asp-controller="Collections" asp-action="Details" asp-route-categoryName="@category.Name"
                                class="category-item text-gray-500 font-semibold hover:text-indigo-600">
                                @category.Name
                            </a>
                        </li>
                    }
                </ul>
            </section>

            <div class="h-[1px] w-full bg-gray-300 my-6"></div>

            <section class="sidebar-section">
                <h3 class="text-lg font-semibold mb-3">Filter by:</h3>
                <ul class="category-list">

                    <li class="category-item">T-Shirt</li>
                    <li class="category-item">T-Shirt</li>
                    <li class="category-item">T-Shirt</li>
                    <li class="category-item">T-Shirt</li>

                </ul>
            </section>
        </div>
    </div>
</aside>