src/Presenters/RookEcomShop.CustomerFrontend/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RookEcomShop.CustomerFrontend.Services.Cart;
using RookEcomShop.CustomerFrontend.Services.Categories;
using RookEcomShop.ViewModels.Dto;

namespace RookEcomShop.CustomerFrontend.ViewComponents
{
    [ViewComponent(Name = "Header")]
    public class HeaderViewComponent : ViewComponent
    {
        private readonly ICategoriesApiClient _categoriesApiClient;
        private readonly ICartApiClient _cartApiClient;
        public HeaderViewComponent(ICategoriesApiClient categoriesApiClient, ICartApiClient cartApiClient)
        {
            _categoriesApiClient = categoriesApiClient;
            _cartApiClient = cartApiClient;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            ViewData["CartCount"] = 0;
            var categories = await _categoriesApiClient.GetCategoriesAsync();
            try
            {
                if (User.Identity?.IsAuthenticated == true)
                {
                    var productsInCart = await _cartApiClient.GetProductsInCart();

                    ViewData["CartCount"] = productsInCart.Count();
                }

                return View(categories.Where(c => c.ParentId == null).ToList().Slice(1, 6));
            }
            catch (System.Exception ex)
            {
                Console.WriteLine(ex);
                return View(new List<CategoryDto>(categories));
            }
        }
    }
}

src/Presenters/RookEcomShop.CustomerFrontend/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RookEcomShop.CustomerFrontend.Services.Categories;

namespace RookEcomShop.CustomerFrontend.ViewComponents
{
    [ViewComponent(Name = "Sidebar")]
    public class SidebarViewComponent : ViewComponent
    {
        private readonly ICategoriesApiClient _categoriesApiClient;
        public SidebarViewComponent(ICategoriesApiClient categoriesApiClient)
        {
            _categoriesApiClient = categoriesApiClient;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoriesApiClient.GetCategoriesAsync();
            return View(categories);
        }
    }
}

src/Presenters/RookEcomShop.CustomerFrontend/Views/Shared/Layouts/_BlankLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/_CommonLayout.cshtml";
}

@section VendorStyles {
    @RenderSection("VendorStyles", required: false)
}

@section PageStyles {
    @RenderSection("PageStyles", required: false)
}

@RenderBody()

@section VendorScripts {
    @RenderSection("VendorScripts", required: false)
}

@section PageScripts {
    @RenderSection("PageScripts", required: false)
}

src/Presenters/RookEcomShop.CustomerFrontend/Views/Shared/Layouts/_CommonLayout.cshtml
@{

}

<!DOCTYPE html>
<html lang="en" class="h-full">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  @{
    string title = ViewData["title"] as string ?? "";

    string appName = TempData.Peek("appName") as string ?? "";

    string productPage = TempData.Peek("productPage") as string ?? "";
  }
  <title>@title | @appName</title>
  <meta name="description" content="" />

  @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="~/RookEcomShop.CustomerFrontend.styles.css" asp-append-version="true" /> *@

  <!-- Core Styles -->
  @await Html.PartialAsync("~/Views/Shared/Sections/_Styles.cshtml")

  <!-- Vendor Styles -->
  @RenderSection("VendorStyles", required: false)

  <!-- Page Styles -->
  @RenderSection("PageStyles", required: false)

  <!-- Include Scripts for customizer, helper, analytics, config -->
  @await Html.PartialAsync("~/Views/Shared/Sections/_ScriptsIncludes.cshtml")
</head>

<body class="w-full h-full flex min-h-screen items-stretch">

  <!-- Layout Content -->
  @RenderBody()
  <!--/ Layout Content -->

  <!-- Core Scripts -->
  @await Html.PartialAsync("~/Views/Shared/Sections/_Scripts.cshtml")

  <!-- Vendor Scripts -->
  @RenderSection("VendorScripts", required: false)


  <!-- Page Scripts-->
  @RenderSection("PageScripts", required: false)


  <script src="~/js/site.js" asp-append-version="true"></script>

</body>

</html>

src/Presenters/RookEcomShop.CustomerFrontend/Views/Shared/Layouts/_ContentSidebarLayout.cshtml
@await Html.PartialAsync("~/Views/Shared/Sections/_Variables.cshtml")
@{
  TempData.Keep();
  Layout = "~/Views/Shared/Layouts/_CommonLayout.cshtml";
}

@section VendorStyles {
  @RenderSection("VendorStyles", required: false)
}

@section PageStyles {
  @RenderSection("PageStyles", required: false)
}

@section VendorScripts {
  @RenderSection("VendorScripts", required: false)
}

@section PageScripts {
  @RenderSection("PageScripts", required: false)
}

<div class="flex-1 flex flex-col min-h-screen">

  <div id="header-wrapper">
    <vc:header></vc:header>

  </div>
  <div class="flex-1 flex">
    <vc:sidebar></vc:sidebar>
    <main role="main" class="container mx-auto p-4 md:p-6">
      @RenderBody()
    </main>
  </div>

  <partial name="~/Views/Shared/Partials/_Footer.cshtml"></partial>
</div>

src/Presenters/RookEcomShop.CustomerFrontend/Views/Shared/Layouts/_LayoutNoSidebar.cshtml
@await Html.PartialAsync("~/Views/Shared/Sections/_Variables.cshtml")
@{
    TempData.Keep();
    Layout = "~/Views/Shared/Layouts/_CommonLayout.cshtml";
}

@section VendorStyles {
    @RenderSection("VendorStyles", required: false)
}

@section PageStyles {
    @RenderSection("PageStyles", required: false)
}

@section VendorScripts {
    @RenderSection("VendorScripts", required: false)
}

@section PageScripts {
    @RenderSection("PageScripts", required: false)
}

<div class="flex-1 flex flex-col min-h-screen">

    <div id="header-wrapper">
        <vc:header></vc:header>
    </div>

    <div class="flex-1">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <partial name="~/Views/Shared/Partials/_Footer.cshtml"></partial>
</div>